let idade = 16
let nome = "PAULO"

// PARA TIRAR CARTEIRA DE MOTORISTA A PESSOA PRECISA TER 18 OU MAIS ANOS DE IDADE.
// se você não tem 18 anos anos não é possivel tirar habilitação

// ei enquanto o usuário efetivarei validação de idade para saber se posso obter uma carteira nacional de habilitação
// paara obter a CNH devo ter idade igual ou superior a 18 anos noato de validação, caso contrario, espero receber uma mensagem informando que não possui idade suficiente.


if (idade >= 18) 
    
    if (idade >= 18) {
        console.log("você tem 18 anos ou mais, pode tirar CNH");
        
}
else {
 console.log("você não tem 18 anos, não pode tirar CNH");
}